@startuml  

rectangle View

rectangle Controller

rectangle Service

rectangle Repository

database SQLite

View --> Controller

Controller --> Service

Service --> Repository

Repository --> SQLite

@enduml